### ISSUE TITLE
Add option to download all textures with one click

### ISSUE THREAD

**Issue by hayleox** [EneaEntertainment/textureUnpacker#1]
For atlases with a lot of textures, it's really tedious to download them one by one. It might be nice to use [jsZip](https://stuk.github.io/jszip/) or something similar to combine all the textures into one easy download.

---

My hacky solution to not have to click endlessly was to write a few lines of JS to automatically click every link. If anyone else wants it, just open your browser's dev tools and paste this in the JS console:
```javascript
var links = document.querySelectorAll("#destContent a");
var i = 0;
function clicky() {
  links[i++].click();
  if (i < links.length) { setTimeout(clicky, 100); }
}
clicky();
```
If you wanted, you could actually just add a "Download All" button that calls my code; it'd just be a bit janky.

**Comment by EneaEntertainment** [comment]
done
